//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.27 at 10:08:52 AM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webcurator.org/xml/harvestagent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.webcurator.xml.harvestagent;
