CREATE INDEX IX_HRC_NAME ON DB_WCT.HARVEST_RESOURCE (HRC_NAME);

CREATE INDEX IX_HRC_HARVEST_RESULT_OID ON DB_WCT.HARVEST_RESOURCE (HRC_HARVEST_RESULT_OID);

CREATE INDEX IDX_FLAGGED ON db_wct.TARGET_INSTANCE (TI_FLAGGED);
ALTER TABLE db_wct.TARGET_INSTANCE CLUSTER ON IDX_FLAGGED;