ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD COLUMN AT_DISPLAY_CHG_REASON TEXT NULL;
ALTER TABLE DB_WCT.ANNOTATIONS ADD COLUMN AN_ALERTABLE bit NOT NULL DEFAULT 0;
ALTER TABLE DB_WCT.SITE ADD COLUMN ST_CREATION_DATE DATETIME;
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD COLUMN TI_FIRST_FROM_TARGET bit NOT NULL DEFAULT 0;
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD COLUMN TI_DISPLAY_CHG_REASON TEXT NULL;
ALTER TABLE DB_WCT.TARGET MODIFY T_EVALUATION_NOTE TEXT NULL;
ALTER TABLE DB_WCT.TARGET MODIFY T_SELECTION_NOTE TEXT NULL;

ALTER TABLE DB_WCT.ABSTRACT_TARGET DROP KEY `AT_NAME`;
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD UNIQUE KEY `AT_NAME_AND_TYPE` (AT_NAME, AT_OBJECT_TYPE);

ALTER TABLE DB_WCT.WCTAUDIT ADD INDEX IX_AUD_DATE (AUD_DATE);
ALTER TABLE DB_WCT.WCTAUDIT ADD INDEX FK_AUD_USER_OID (AUD_USER_OID), add constraint FK_AUD_USER_OID foreign key (AUD_USER_OID) references DB_WCT.WCTUSER (USR_OID);
ALTER TABLE DB_WCT.WCTAUDIT ADD INDEX FK_AUD_AGENCY_OID (AUD_AGENCY_OID), add constraint FK_AUD_AGENCY_OID foreign key (AUD_AGENCY_OID) references DB_WCT.AGENCY (AGC_OID);


update DB_WCT.SITE s set s.st_creation_date = (select min(pe_creation_date) from DB_WCT.PERMISSION where pe_site_id=s.st_oid);

CREATE OR REPLACE VIEW DB_WCT.ABSTRACT_TARGET_GROUPTYPE_VIEW AS 
 SELECT a.at_oid, a.at_desc, a.at_name, a.at_owner_id, a.at_prof_override_oid, a.at_state, a.t_profile_id, a.at_object_type, a.at_creation_date, a.at_reference, a.at_profile_note, a.at_dublin_core_oid, a.at_access_zone, a.at_display_target, a.at_display_note, tg.tg_type
   FROM DB_WCT.ABSTRACT_TARGET a
   LEFT JOIN DB_WCT.TARGET_GROUP tg ON a.at_oid = tg.tg_at_oid;
   
ALTER TABLE DB_WCT.HARVEST_STATUS ADD COLUMN HS_APP_VERSION varchar(255);
ALTER TABLE DB_WCT.HARVEST_STATUS ADD COLUMN HS_HRTX_VERSION varchar(255);   

ALTER TABLE DB_WCT.SCHEDULE ADD COLUMN S_LAST_PROCESSED_DATE DATETIME DEFAULT '2001-01-01 00:00:00';   
ALTER TABLE DB_WCT.SCHEDULE ADD INDEX IX_SHED_PROC_DATE (S_LAST_PROCESSED_DATE);
ALTER TABLE DB_WCT.SCHEDULE ADD INDEX IX_SHED_NEXT_TIME (S_NEXT_SCHEDULE_TIME);