ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD (AT_DISPLAY_CHG_REASON varchar2(1000));
ALTER TABLE DB_WCT.ANNOTATIONS ADD (AN_ALERTABLE NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE DB_WCT.SITE ADD (ST_CREATION_DATE TIMESTAMP(9));
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD (TI_FIRST_FROM_TARGET NUMBER(1,0) DEFAULT 0 NOT NULL);
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD (TI_DISPLAY_CHG_REASON varchar2(1000));
ALTER TABLE DB_WCT.TARGET MODIFY T_EVALUATION_NOTE VARCHAR2(1000) NULL;
ALTER TABLE DB_WCT.TARGET MODIFY T_SELECTION_NOTE VARCHAR2(1000) NULL;

ALTER TABLE DB_WCT.ABSTRACT_TARGET DROP CONSTRAINT AT_NAME;
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD CONSTRAINT AT_NAME_AND_TYPE UNIQUE (AT_NAME, AT_OBJECT_TYPE);

CREATE INDEX IX_AUD_DATE ON DB_WCT.WCTAUDIT (AUD_DATE);
ALTER TABLE DB_WCT.WCTAUDIT ADD CONSTRAINT FK_AUD_USER_OID foreign key (AUD_USER_OID) references DB_WCT.WCTUSER (USR_OID);
ALTER TABLE DB_WCT.WCTAUDIT ADD CONSTRAINT FK_AUD_AGENCY_OID foreign key (AUD_AGENCY_OID) references DB_WCT.AGENCY (AGC_OID);

update DB_WCT.SITE s set s.st_creation_date = (select min(pe_creation_date) from permission where pe_site_id=s.st_oid);

CREATE OR REPLACE VIEW DB_WCT.ABSTRACT_TARGET_GROUPTYPE_VIEW AS 
 SELECT a.at_oid, a.at_desc, a.at_name, a.at_owner_id, a.at_prof_override_oid, a.at_state, a.t_profile_id, a.at_object_type, a.at_creation_date, a.at_reference, a.at_profile_note, a.at_dublin_core_oid, a.at_access_zone, a.at_display_target, a.at_display_note, tg.tg_type
   FROM DB_WCT.ABSTRACT_TARGET a
   LEFT JOIN DB_WCT.TARGET_GROUP tg ON a.at_oid = tg.tg_at_oid;

GRANT SELECT, UPDATE, INSERT, DELETE ON DB_WCT.ABSTRACT_TARGET_GROUPTYPE_VIEW TO usr_wct;

ALTER TABLE DB_WCT.HARVEST_STATUS ADD COLUMN HS_APP_VERSION varchar2(255);
ALTER TABLE DB_WCT.HARVEST_STATUS ADD COLUMN HS_HRTX_VERSION varchar2(255);

ALTER TABLE DB_WCT.SCHEDULE ADD (S_LAST_PROCESSED_DATE TIMESTAMP(9) DEFAULT to_timestamp('2001-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'));
CREATE INDEX IX_SHED_PROC_DATE ON DB_WCT.SCHEDULE (S_LAST_PROCESSED_DATE);
CREATE INDEX IX_SHED_NEXT_TIME ON DB_WCT.SCHEDULE (S_NEXT_SCHEDULE_TIME);
