-- PROFILE

alter table DB_WCT.PROFILE add (P_HARVESTER_TYPE varchar2(40));
update DB_WCT.PROFILE set P_HARVESTER_TYPE='HERITRIX1';
alter table DB_WCT.PROFILE modify P_HARVESTER_TYPE varchar2(40) not null;

alter table DB_WCT.PROFILE add (P_DATA_LIMIT_UNIT varchar2(40));
update DB_WCT.PROFILE set P_DATA_LIMIT_UNIT='B' where P_HARVESTER_TYPE='HERITRIX3';

alter table DB_WCT.PROFILE add (P_MAX_FILE_SIZE_UNIT varchar2(40));
update DB_WCT.PROFILE set P_MAX_FILE_SIZE_UNIT='B' where P_HARVESTER_TYPE='HERITRIX3';

alter table DB_WCT.PROFILE add (P_TIME_LIMIT_UNIT varchar2(40));
update DB_WCT.PROFILE set P_TIME_LIMIT_UNIT='SECOND' where P_HARVESTER_TYPE='HERITRIX3';

-- PROFILE_OVERRIDES

alter table DB_WCT.PROFILE_OVERRIDES add (PO_H3_DOC_LIMIT number(10,0), PO_H3_DATA_LIMIT double precision, PO_H3_DATA_LIMIT_UNIT varchar2(40),
PO_H3_TIME_LIMIT double precision, PO_H3_TIME_LIMIT_UNIT varchar2(40), PO_H3_MAX_PATH_DEPTH number(10,0), PO_H3_MAX_HOPS number(10,0),
PO_H3_MAX_TRANS_HOPS number(10,0), PO_H3_IGNORE_ROBOTS varchar2(10), PO_H3_IGNORE_COOKIES number(1,0), PO_H3_OR_DOC_LIMIT number(1,0),
PO_H3_OR_DATA_LIMIT number(1,0), PO_H3_OR_TIME_LIMIT number(1,0), PO_H3_OR_MAX_PATH_DEPTH number(1,0), PO_H3_OR_MAX_HOPS number(1,0),
PO_H3_OR_MAX_TRANS_HOPS number(1,0), PO_H3_OR_IGNORE_ROBOTS number(1,0), PO_H3_OR_IGNORE_COOKIES number(1,0), PO_H3_OR_BLOCK_URL number(1,0),
PO_H3_OR_INCL_URL number(1,0));

update DB_WCT.PROFILE_OVERRIDES set PO_H3_IGNORE_COOKIES = 0, PO_H3_OR_DOC_LIMIT = 0, PO_H3_OR_DATA_LIMIT = 0, PO_H3_OR_TIME_LIMIT = 0, PO_H3_OR_MAX_PATH_DEPTH = 0,
PO_H3_OR_MAX_HOPS = 0, PO_H3_OR_MAX_TRANS_HOPS = 0, PO_H3_OR_IGNORE_ROBOTS = 0, PO_H3_OR_IGNORE_COOKIES = 0, PO_H3_OR_BLOCK_URL = 0, PO_H3_OR_INCL_URL = 0;

create table DB_WCT.PO_H3_BLOCK_URL (PBU_PROF_OVER_OID number(19,0) not null, PBU_FILTER varchar2(255), PBU_IX number(10,0) not null, primary key (PBU_PROF_OVER_OID, PBU_IX));
create table DB_WCT.PO_H3_INCLUDE_URL (PIU_PROF_OVER_OID number(19,0) not null, PIU_FILTER varchar2(255), PIU_IX number(10,0) not null, primary key (PIU_PROF_OVER_OID, PIU_IX));

alter table DB_WCT.PO_H3_BLOCK_URL add constraint PBU_FK_1 foreign key (PBU_PROF_OVER_OID) references DB_WCT.PROFILE_OVERRIDES;
alter table DB_WCT.PO_H3_INCLUDE_URL add constraint PIU_FK_1 foreign key (PIU_PROF_OVER_OID) references DB_WCT.PROFILE_OVERRIDES;

GRANT SELECT, INSERT, UPDATE, DELETE ON DB_WCT.PO_H3_BLOCK_URL TO USR_WCT;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_WCT.PO_H3_INCLUDE_URL TO USR_WCT;

alter table DB_WCT.PROFILE add (IMPORTED number(1,0) default 0 not null);
