alter table DB_WCT.PROFILE add (P_HARVESTER_TYPE varchar2(40));
update DB_WCT.PROFILE set P_HARVESTER_TYPE='HERITRIX1';
alter table DB_WCT.PROFILE modify P_HARVESTER_TYPE varchar2(40) not null;

alter table DB_WCT.PROFILE add (P_DATA_LIMIT_UNIT varchar2(40));
update DB_WCT.PROFILE set P_DATA_LIMIT_UNIT='B' where P_HARVESTER_TYPE='HERITRIX3';

alter table DB_WCT.PROFILE add (P_MAX_FILE_SIZE_UNIT varchar2(40));
update DB_WCT.PROFILE set P_MAX_FILE_SIZE_UNIT='B' where P_HARVESTER_TYPE='HERITRIX3';

alter table DB_WCT.PROFILE add (P_TIME_LIMIT_UNIT varchar2(40));
update DB_WCT.PROFILE set P_TIME_LIMIT_UNIT='SECOND' where P_HARVESTER_TYPE='HERITRIX3';

