insert into DB_WCT.AGENCY (AGC_OID,AGC_NAME,AGC_ADDRESS,AGC_SHOW_TASKS) values (0,'bootstrap', 'NA', 1);
insert into DB_WCT.WCTUSER (USR_OID, USR_ACTIVE, USR_EMAIL, USR_EXTERNAL_AUTH, USR_FIRSTNAME, USR_LASTNAME, USR_NOTIFICATIONS_BY_EMAIL, USR_PASSWORD, USR_USERNAME, USR_FORCE_PWD_CHANGE, USR_AGC_OID, USR_TASKS_BY_EMAIL,  USR_NOTIFY_ON_GENERAL,  USR_NOTIFY_ON_WARNINGS) values (0, 1, 'bootstrap@sytec.co.nz', 0, 'System', 'Bootstrap', 0, '2cef312836577798919e66999e80487a349b83bd', 'bootstrap', 0,0,0,0,0);
insert into DB_WCT.WCTROLE (ROL_OID, ROL_DESCRIPTION, ROL_NAME, ROL_AGENCY_OID) values(0,'Bootstrap Role', 'Bootstrap Role',0);
insert into DB_WCT.USER_ROLE (URO_USR_OID, URO_ROL_OID) values (0,0);
insert into DB_WCT.ROLE_PRIVILEGE (PRV_OID, PRV_CODE, PRV_ROLE_OID, PRV_SCOPE) values (0,'LOGIN',0,0);
insert into DB_WCT.ROLE_PRIVILEGE (PRV_OID, PRV_CODE, PRV_ROLE_OID, PRV_SCOPE) values (-1,'MANAGE_AGENCIES',0,0);
insert into DB_WCT.ROLE_PRIVILEGE (PRV_OID, PRV_CODE, PRV_ROLE_OID, PRV_SCOPE) values (-2,'MANAGE_USERS',0,0);
insert into DB_WCT.ROLE_PRIVILEGE (PRV_OID, PRV_CODE, PRV_ROLE_OID, PRV_SCOPE) values (-3,'MANAGE_ROLES',0,0);
insert into DB_WCT.ROLE_PRIVILEGE (PRV_OID, PRV_CODE, PRV_ROLE_OID, PRV_SCOPE) values (-4,'GRANT_CROSS_AGENCY_USER_ADMIN',0,0); 

insert into DB_WCT.HEATMAP_CONFIG (HM_OID, HM_NAME, HM_DISPLAY_NAME, HM_COLOR, HM_THRESHOLD_LOWEST) values (1, 'low','Low','8FBC8F',1);
insert into DB_WCT.HEATMAP_CONFIG (HM_OID, HM_NAME, HM_DISPLAY_NAME, HM_COLOR, HM_THRESHOLD_LOWEST) values (2, 'medium','Medium','F0E68C',7);
insert into DB_WCT.HEATMAP_CONFIG (HM_OID, HM_NAME, HM_DISPLAY_NAME, HM_COLOR, HM_THRESHOLD_LOWEST) values (3, 'high','High','FF6347',12);

drop table DB_WCT.URL_PERMISSION_MAPPING_VIEW
drop table DB_WCT.ABSTRACT_TARGET_SCHEDULE_VIEW
drop table DB_WCT.ABSTRACT_TARGET_GROUPTYPE_VIEW


create view DB_WCT.URL_PERMISSION_MAPPING_VIEW as  SELECT upm.upm_oid, upm.upm_domain, p.pe_oid, p.pe_end_date, p.pe_owning_agency_id, up.up_pattern, st.st_active   FROM DB_WCT.URL_PERMISSION_MAPPING upm   JOIN DB_WCT.PERMISSION p ON upm.upm_permission_id = p.pe_oid   JOIN DB_WCT.URL_PATTERN up ON upm.upm_url_pattern_id = up.up_oid   JOIN DB_WCT.SITE st ON p.pe_site_id = st.st_oid

create view DB_WCT.ABSTRACT_TARGET_SCHEDULE_VIEW as SELECT (abt.at_oid || ',') || s.s_oid AS thekey,        CASE abt.at_object_type            WHEN 1 THEN 'Target'            ELSE 'Group'        END AS at_object_type_desc, abt.at_name, abt.at_state, u.usr_username, a.agc_name, s.s_oid, s.s_start, s.s_end, s.s_type, s.s_cron   FROM DB_WCT.ABSTRACT_TARGET abt   RIGHT JOIN DB_WCT.SCHEDULE s ON s.s_abstract_target_id = abt.at_oid   JOIN DB_WCT.WCTUSER u ON abt.at_owner_id = u.usr_oid   JOIN DB_WCT.AGENCY a ON u.usr_agc_oid = a.agc_oid  ORDER BY abt.at_name, s.s_oid  

create view DB_WCT.ABSTRACT_TARGET_GROUPTYPE_VIEW as  SELECT a.at_oid, a.at_desc, a.at_name, a.at_owner_id, a.at_prof_override_oid, a.at_state, a.t_profile_id, a.at_object_type, a.at_creation_date, a.at_reference, a.at_profile_note, a.at_dublin_core_oid, a.at_access_zone, a.at_display_target, a.at_display_note, tg.tg_type   FROM db_wct.abstract_target a   LEFT JOIN db_wct.target_group tg ON a.at_oid = tg.tg_at_oid

INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (1, 'Crawl Runtime', 'Elapsed time of crawl in milliseconds', 10, -10, 25200000, 60000, 0, 'millisecond', 0, 0);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (2, 'URLs Downloaded', 'The number of URLs downloaded for the site', 10, -10, NULL, 1, 0, 'integer', 1, 0);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (3, 'Delist', 'Number of times that the same content is downloaded before a target is flagged for de-listing (based on the number of bytes downloaded)', NULL, NULL, 2, NULL, 0, 'integer', 0, 0);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (4, 'Heritrix Error Codes', 'The number of occurances of a Heritrix Error Code (any negative code + 403, 404 and 301)', 10, 0, 1, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (5, 'Long URIs', 'Occurances of a URI exceeding 125 characters', 10, -10, 1, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (6, 'Matching URIs', 'The number of URIs from this crawl that also appeared in the reference crawl', NULL, NULL, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (7, 'Missing URIs', 'The URIs that appear in the reference crawl but do not appear in the current crawl', 5, 0, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (8, 'New URIs', 'The URIs that appear in the current crawl that did not appear in the reference crawl', 10, 0, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (9, 'Off Scope URIs', 'The number of URIs that do not belong to a subdomain of the targets seeds', 5, 0, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (10, 'Robots.txt entries disallowed', 'The number of ''DISALLOWED'' entries in the site''s ROBOTS.TXT file', 10, -10, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (11, 'Unknown MIME Types', 'The number of distinct unrecognised MIME types encountered for the crawl', 10, 0, 1, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (12, 'Sub Domains', 'The number of domains in the root domain for the site', 15, 0, NULL, NULL, 0, 'integer', 1, 1);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (13, 'Content Downloaded', 'Number of bytes downloaded', 10, -10, NULL, 1048576, 0, 'byte', 1, 0);
INSERT INTO DB_WCT.INDICATOR_CRITERIA (ic_oid, ic_name, ic_description, ic_upper_limit_percentage, ic_lower_limit_percentage, ic_upper_limit, ic_lower_limit, ic_agc_oid, ic_unit, ic_show_delta, ic_enable_report) VALUES (14, 'Repeating URI Patterns', 'URIs containing repeating path segments', 10, -10, 1, NULL, 0, 'integer', 1, 1);
