-- New Column: DB_WCT.AT_ACCESS_ZONE
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD(at_access_zone NUMBER(2,0) DEFAULT 0 NOT NULL) ;
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD CONSTRAINT chk_access_zone CHECK (at_access_zone in (0, 1, 2));

-- New Column: DB_WCT.AT_DISPLAY_TARGET
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD (at_display_target NUMBER(1,0) DEFAULT 1 NOT NULL);

-- New Column: DB_WCT.AT_DISPLAY_NOTE
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD (at_display_note VARCHAR2(4000));

-- New Column: DB_WCT.TI_DISPLAY_TARGET_INSTANCE
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD(ti_display_target_instance NUMBER(1,0) DEFAULT 1 NOT NULL);

-- New Column: DB_WCT.TI_DISPLAY_NOTE
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD(ti_display_note VARCHAR2(4000));

COMMIT;