-- New Column: DB_WCT.AT_ACCESS_ZONE
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD COLUMN at_access_zone integer NOT NULL DEFAULT 0;
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD CONSTRAINT chk_access_zone CHECK (at_access_zone in (0, 1, 2));

-- New Column: DB_WCT.AT_DISPLAY_TARGET
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD COLUMN at_display_target boolean NOT NULL DEFAULT true;

-- New Column: DB_WCT.AT_DISPLAY_NOTE
ALTER TABLE DB_WCT.ABSTRACT_TARGET ADD COLUMN at_display_note character varying(4000);

-- New Column: DB_WCT.TI_DISPLAY_TARGET_INSTANCE
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD COLUMN ti_display_target_instance boolean NOT NULL DEFAULT true;

-- New Column: DB_WCT.TI_DISPLAY_NOTE
ALTER TABLE DB_WCT.TARGET_INSTANCE ADD COLUMN ti_display_note character varying(4000);
